# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: todos-with-undo"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-with-undo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-with-undo
  template:
    metadata:
      labels:
        app: todos-with-undo
    spec:
      containers:
        - name: server
          image: todos-with-undo
          ports:
          - containerPort: 3000
          env:
          - name: PORT
            value: "3000"


