
apiVersion: v1
kind: Service
metadata:
  name: emojisearch-external
spec:
  type: LoadBalancer
  selector:
    app: todos-with-undo
  ports:
  - name: http
    port: 80
    targetPort: 8080
